ALTER TABLE USUARIO DROP FOREIGN KEY FK_USUARIO_ROL_ID
ALTER TABLE OPCIONES_MENU DROP FOREIGN KEY FK_OPCIONES_MENU_MENU_ID
ALTER TABLE OPCIONES_MENU DROP FOREIGN KEY FK_OPCIONES_MENU_OPCION_ID
ALTER TABLE MENUS_ROL DROP FOREIGN KEY FK_MENUS_ROL_ROL_ID
ALTER TABLE MENUS_ROL DROP FOREIGN KEY FK_MENUS_ROL_MENU_ID
DROP TABLE categoria
DROP TABLE PRODUCT
DROP TABLE MENU
DROP TABLE OPCION
DROP TABLE ROL
DROP TABLE USUARIO
DROP TABLE OPCIONES_MENU
DROP TABLE MENUS_ROL
